spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.example: DEBUG

jwt:
  secret: ${JWT_SECRET:jwt.super.secret.key.jwt.super.secret.key}
  token_life_time: ${JWT_LIFE_TIME:7}

admin:
  email: admin@mail.com
  password: password
